LangString addOrReinstall ${LANG_SIMPCHINESE} "重新安装"
LangString alreadyInstalled ${LANG_SIMPCHINESE} "检测到已安装"
LangString alreadyInstalledLong ${LANG_SIMPCHINESE} "检测到 ${PRODUCTNAME} ${VERSION} 已安装。请选择要执行的操作，点击「下一步」继续。"
LangString appRunning ${LANG_SIMPCHINESE} "{{product_name}} 正在运行！请关闭后再试。"
LangString appRunningOkKill ${LANG_SIMPCHINESE} "{{product_name}} 正在运行！$\n点击确定以终止运行。"
LangString chooseMaintenanceOption ${LANG_SIMPCHINESE} "请选择要执行的操作"
LangString choowHowToInstall ${LANG_SIMPCHINESE} "请选择安装 ${PRODUCTNAME} 的方式"
LangString createDesktop ${LANG_SIMPCHINESE} "创建桌面快捷方式"
LangString dontUninstall ${LANG_SIMPCHINESE} "不卸载，直接覆盖安装"
LangString dontUninstallDowngrade ${LANG_SIMPCHINESE} "不卸载（此安装程序禁止未卸载就进行版本降级的操作）"
LangString failedToKillApp ${LANG_SIMPCHINESE} "无法终止 {{product_name}}。请关闭后再试。"
LangString installingWebview2 ${LANG_SIMPCHINESE} "正在安装 WebView2..."
LangString newerVersionInstalled ${LANG_SIMPCHINESE} "检测到系统中已安装更新版本的 ${PRODUCTNAME}。不建议安装旧版本。如果确需安装，请先卸载当前版本。请选择要执行的操作，点击「下一步」继续。"
LangString older ${LANG_SIMPCHINESE} "旧的"
LangString olderOrUnknownVersionInstalled ${LANG_SIMPCHINESE} "检测到系统中已存在 ${PRODUCTNAME}（版本 $R4）。建议先卸载旧版本再安装新版本。请选择要执行的操作，点击「下一步」继续。"
LangString silentDowngrades ${LANG_SIMPCHINESE} "降级操作在此安装程序上已禁用，无法进行安静安装，请使用图形操作界面。$\n"
LangString unableToUninstall ${LANG_SIMPCHINESE} "无法卸载！"
LangString uninstallApp ${LANG_SIMPCHINESE} "卸载旧版本（卸载后将重新安装）"
LangString uninstallBeforeInstalling ${LANG_SIMPCHINESE} "卸载旧版本后重新安装"
LangString unknown ${LANG_SIMPCHINESE} "未知"
LangString webview2AbortError ${LANG_SIMPCHINESE} "无法安装 WebView2！没有它，此应用就无法运行。尝试重启安装程序。"
LangString webview2DownloadError ${LANG_SIMPCHINESE} "错误：无法下载 WebView2 - $0"
LangString webview2DownloadSuccess ${LANG_SIMPCHINESE} "WebView2 引导程序下载成功"
LangString webview2Downloading ${LANG_SIMPCHINESE} "正在下载 WebView2 引导程序..."
LangString webview2InstallError ${LANG_SIMPCHINESE} "错误：安装 WebView2 时失败，错误代码：$1"
LangString webview2InstallSuccess ${LANG_SIMPCHINESE} "成功安装 WebView2"
LangString deleteAppData ${LANG_SIMPCHINESE} "删除应用程序数据"
